azure/configure-azurefiles.yml
azure/create-ocp-cluster.sh
azure/deploy.sh
azure/ocp-terraform/azure_infra/ocp-install.tf
azure/ocp-terraform/azure_infra/variables.tf

Creating a azurefile-storage account with uniquestring in it. so that we can have multiple OCP clusters under same subscribtion.

create storage account with uniquestr in it

---

azure/master-arm/mainTemplate-dev.json
azure/master-arm/mainTemplate.json

Added following changes to ARM template:
- Create Log Analytics Workspace & Custom Logs
- Install OMSAgent on Bootnode VM.
- Configure OMSAgent with Cloud Analytics Workspace to enable log push.

Implemented Azure Log Analytics to send the MAs deployment logs to Log Analytics Workspace

---

azure/deploy-cp4d.sh

Added a script to deploy `CP4D` on the existing **MAS+Manage** offering in azure.

Added deploy-cp4d.sh in azure/ sub directory

---

aws/deploy.sh
azure/deploy.sh
azure/master-arm/byol-ipi/mainTemplate-dev.json
azure/master-arm/byol-ipi/mainTemplate.json

Removed SBO Installation step from script and also removed DependencyAgentLinux extension from ARM Template.

Removed SBO Installation and Removed Azure DependencyAgent

---

init.sh

Stack creation failed as its not in current directory

stackcreationfailed

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.json
aws/master-cft/byol-existing-ocp/cft-mas-core.json

1. In case of **Conditions**, both **NoExistingOCPCluster** and **ExistingOCPCluster** have to be removed as the assumption is - this needs to be used only for existing OCP Cluster
2. In case of **Metadata** and **Parameters**
a. **OCPPullSecret** has to be removed
b. **EntitledRegistryKey** has to be removed
4. In case of **Outputs**, 
a. Change version
b. **ClusterUniqueString** has to be removed
c. **OpenShiftConsoleURL** has to be removed
d. **OpenShiftAPIURL** has to be removed
e. **MASInitialSetupUrl** has to be removed
f. **MASInitialSetupURLLogin** needs to be retained
g. **MASAdminUrl** has to be removed 
h. **MASAdminUrlLogin** has to be retained
i. **MASWorkspaceUrl** has to be removed
j. **MASWorkspaceUrlLogin** has to be retained
k. **OCPPullSecret** has to be removed
l. …

Removed Conditions and some of the Outputs

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.json
aws/master-cft/byol-upi/cft-mas-core-dev.json
init.sh

Added null check condition _(and default setting)_ for `$ENV_TYPE` just in case any of the CFTs dont pass the variable

Byol existing ocp

---

aws/master-cft/byol-existing-ocp/cft-mas-core.json
aws/master-cft/byol-upi/cft-mas-core-dev.json
aws/master-cft/byol-upi/cft-mas-core.json

Removed default CIDR set for UPI

---

init.sh

Please review , Its for Manage=8.4.x

ManageVersion

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml

Added the `CFT` in `YAML` format. I have not yet removed the `JSON` format

Added CFT in YAML format

---

aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml

Pushing fix for output urls

---

pre-validate.sh

Pushing fix for defect 10007

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core.yaml
pre-requisite.sh
script-functions.bash

- added code to generate random string with alphabet
- added check to skip SLS and UDS check in case of external UDS or SLS

Random string generation and external SLS and UDS changes

---

aws/aws-product-codes.config
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml

Hi @vaibhavkulkarniibm and @amitmangalvedkar , Can you please review this

Changesforproductcode

---

.project
aws/deploy-cp4d.sh
aws/deploy.sh
aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/ocp-terraform/ocs/variables.tf
helper.sh
pre-validate.sh

@amitmangalvedkar - I have checked in code changes for supporting 6 new regions on AWS..Please review this PR & approve it if you feel changes are okay. Thanks

Checking in code changes for supporting 6 new regions on AWS..

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml

Adding AMI Id to all the regions.

Adding AMI Id to all the regions

---

aws/deploy-cp4d.sh
aws/deploy.sh
azure/deploy-cp4d.sh
azure/deploy.sh

https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/4#issuecomment-50505147

[patch] CP4D version set to 4.5.0 (Azure + AWS)

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-ipi/cft-mas-core.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-upi/cft-mas-core.yaml
init.sh

Can u please review for the output values fix

OutputValues changes

---

aws/bootnode-ami/prepare-bootnode-ami.sh
azure/bootnode-image/bootnode-image-step-1.sh
azure/bootnode-image/prepare-bootnode-image.sh

this is fix for openshift 410 in UPI where opeshift-install is used 
@amitmangalvedkar @padmankosalaram - Can u please review this

Mas89 alpha shajsyed

---

init.sh

tracker-hyperscalers/issues/82

[minor] set MAS_CATALOG_VERSION to v8-amd64

---

gcp/create-bastion-host.sh
gcp/deploy.sh
gcp/ocp-bastion-host/main.tf
gcp/ocp-bastion-host/variables.tf

Added bastion host creation code for gcp.

gcp bastion host code

---

helper.sh
init.sh

tracker-hyperscalers/issues/108

[patch] azure hyperscaler annotations

---

azure/bootnode-image/bootnode-image-step-1.sh
azure/bootnode-image/prepare-bootnode-image.sh

Python3.9 update in RHEL8 for azure

Mas89 alpha shajpy39

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml

Fixed many issues around in all 6 CFT files around cloning branches which was inconsistent (as it was cloning ocp410 branch in some cft files & mas89-alpha in others..In prod cft files, made it to point to -b clone 2.0.1 such that there will be consistency & when we go for production update for MAS 8.9, we can change it to 3.0 or 8.9), python version corrected to point to 3.9 from 3.8, & operationalmode missing in UPI CFT.

Corrections to CFT files (both dev & prod)

---

aws/master-cft/byol-upi/cft-mas-core.yaml

@padmankosalaram - Fixed the issue on operational mode..pls review now..

Fixed another issue in UPI CFT..

---

aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-ipi/cft-mas-core.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-upi/cft-mas-core.yaml

Updated Paid offering CFT's with Item 1 issue fix & python, AMI ID..Please review the same..

Updated Paid offering CFT's with Item 1 issue fix & python, AMI ID..

---

aws/ocp-terraform/ocs/templates.tf

tracker-hyperscalers/issues/93

[minor] - AWS ODF operator related change

---

init.sh

changed the `MAS_DEVOPS_COLLECTION_VERSION` to 12.3.2 so as to make it work on Azure

changed the  to 12.3.2

---

azure/master-arm/byol-existing-ocp/createUiDefinition.json

tracker-hyperscalers/issues/135

[patch] case correction

---

aws/cleanup-mas-deployment.sh

[patch] cleanup vpc peering connection filtered as AccepterVpcInfo

---

aws/deploy.sh
azure/deploy.sh
init.sh

https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/299

[patch] 8.9.3-rc - Changes to deploy 8.9.3 using static catalog

---

aws/cleanup-s3-bucket.sh

https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/301

[patch] s3 bucket cleanup script

---

aws/bootnode-ami/prepare-bootnode-ami.sh
aws/deploy.sh
aws/ocp-terraform/linux-prereq-install.sh
aws/ocp-terraform/mac-prereq-install.sh
aws/ocp-terraform/ocp/variables.tf
aws/ocp-terraform/ocs/gp2.yaml
aws/ocp-terraform/ocs/ocs-storagecluster-ceph-rbd.yaml
aws/ocp-terraform/ocs/ocs-storagecluster-cephfs.yaml
aws/ocp-terraform/ocs/openshift-storage.noobaa.io.yaml
aws/ocp-terraform/ocs/templates.tf
aws/ocp-terraform/variables.tf

Checking in code changes to support OCP 4.12.18 in AWS..

Checking in code changes to support OCP 4.12.18 in AWS..

---

aws/deploy.sh

Code check-in to ensure only gp2 is set as default storage class

Code check-in to ensure only gp2 is set as default storage class

---

script-functions.bash

Checking in code fix for ExistingOCP flow issue.
Details of the issue & scenarios tested are covered in this GIthub issue --> https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/326
I have referred this link & based on this removed 4.8.x entries --> https://pages.github.ibm.com/maximoappsuite/support/compatability-matrix/#red-hat-openshift-container-platform-compatibility

Checking in code fix for ExistingOCP flow issue..

---

aws/deploy.sh
aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
init.sh

Adding code on top of Nataraj'scode for UDS

Suds install

---

aws/deploy.sh

This change is only for troubleshooting the internal db2 issue

[patch] troubleshoot internal db2 issue

---

aws/deploy.sh

workaround code fix for internal db2 issue..

workaround code fix for internal db2 issue..

---

aws/cleanup-mas-deployment.sh
aws/deploy.sh
init.sh

Code changes for fixing logging issue & removing leading spaces from kubeadmin secret & deleting the kubeadmin secret when cleanup script is executed.

code changes for logging & removing leading spaces from kubeadmin secret

---

aws/deploy.sh
helper.sh
pre-requisite.sh
pre-validate.sh
script-functions.bash

@padmankosalaram @shajeena @amitmangalvedkar - I have fixed the comment given by Padmanabhan in PR --> https://github.com/ibm-mas/multicloud-bootstrap/pull/242 & have removed the internal DB2 support if existing cluster is ROSA as I tested internal db2 flow for 3-4 times & it's failing. Please review this PR.

ROSA changes..

---

aws/deploy.sh
pre-validate.sh
script-functions.bash

@shajeena @amitmangalvedkar - Please review this PR. It includes changes to support ROSA 4.14.x version and internal DB2 on ROSA.. Both these flows are verified. MAS + Manage is verified on Oracle.

changes to support ROSA 4.14.x and internal DB2 on ROSA..

---

aws/deploy.sh
aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-ipi/cft-mas-core.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-upi/cft-mas-core.yaml
aws/notify.sh
aws/ocp-terraform/ocs/templates.tf
aws/ocp-terraform/variables.tf

Custom CIDR supporting code & other code changes for MAS 9 on AWS..

Custom CIDR supporting code & other code changes for MAS 9 on AWS..

---

aws/deploy.sh

Changes for ROSA..

---

aws/bootnode-ami/prepare-bootnode-ami.sh

Ansible runtime version update to run latest ansible collections..

Ansible runtime version update to run latest ansible collections..

---

aws/bootnode-ami/prepare-bootnode-ami.sh

changes to support OCP 4.15.x

---

aws/ocp-terraform/linux-prereq-install.sh
aws/ocp-terraform/mac-prereq-install.sh
aws/ocp-terraform/ocp/variables.tf
aws/ocp-terraform/ocs/templates.tf
aws/ocp-terraform/variables.tf

Changes specific to AWS for OCP 4.15.x support..

Changes specific to AWS for OCP 4.15.x support..

---

aws/ocp-terraform/scripts/aws_resource_quota
aws/ocp-terraform/scripts/aws_resource_quota_validation.py
aws/ocp-terraform/scripts/aws_resource_quota_validation.sh

code changes as per AWS side changes on s3 bucket quota..
Please see this --> https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-up-1-million-buckets-per-aws-account/

code changes as per AWS side changes on s3 bucket quota..

---

azure/bootnode-image/prepare-bootnode-image.sh
azure/ocp-terraform/azure_infra/variables.tf

[patch]Upgrading ocp version

---

aws/master-cft/byol-govcloud-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-govcloud-upi/cft-mas-core.yaml

Adding CFT files for GovCloud listing for both UPI & existing OCP cluster flow into the repository for reference or usage whenever it's needed.

Adding CFT files for GovCloud listing..

---

aws/cleanup-mas-deployment.sh

Updating this script file with GovCloud region entries..

Updating with GovCloud region entries..

---

aws/master-cft/byol-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/byol-existing-ocp/cft-mas-core.yaml
aws/master-cft/byol-ipi/cft-mas-core-dev.yaml
aws/master-cft/byol-ipi/cft-mas-core.yaml
aws/master-cft/byol-upi/cft-mas-core-dev.yaml
aws/master-cft/byol-upi/cft-mas-core.yaml

Updates to CFT files with latest AMI Id's for BYOL listings..

Updates to CFT files with latest AMI Id's for BYOL listings..

---

aws/master-cft/paid-existing-ocp/cft-mas-core-dev.yaml
aws/master-cft/paid-existing-ocp/cft-mas-core.yaml
aws/master-cft/paid-ipi/cft-mas-core-dev.yaml
aws/master-cft/paid-ipi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-ipi/cft-mas-core.yaml
aws/master-cft/paid-upi/cft-mas-core-dev.yaml
aws/master-cft/paid-upi/cft-mas-core-without-ocp-license.yaml
aws/master-cft/paid-upi/cft-mas-core.yaml

Updates to CFT files with latest AMI Id's for Paid listings..

Updates to CFT files with latest AMI Id's for Paid listings..
